### ISSUE TITLE
Smoother movement via transition

### ISSUE THREAD

**Issue by crowtower** [loganstellway/ZoomIt#6]
Hi, love this project!
Just two code suggestions to make movement smoother (which is currently a little jerky).

In the css:  (this makes the large image open smoothly and move smoothly)
`insert line 25:   transition: transform .1s ease, opacity .2s ease;`

In the js:  (this just delays removing the instance to give fade out transition time to work)
`line 162 change to:   setTimeout(function(){ options.getZoomInstance().remove(); }, 500);`

Cheers

**Comment by LoganGS** [comment]
Submit a merge request! :D


KRIS CHASE
Partner / Technology Director







14988 Sand Canyon Ave
Studio 4
Irvine, CA 92618
<https://www.google.com/maps/place/14988+Sand+Canyon+Ave,+Irvine,+CA+92618/>



Phone: 877.728.8901 <8777288901> ext. 314
Mobile: 949.667.4035 <9496674035>
kris@gigasavvy.com
http://gigasavvy.com <http://www.gigasavvy.com/>


Facebook <https://www.facebook.com/GigaSavvy> Instagram
<https://instagram.com/gigasavvy/> LinkedIn
<https://www.linkedin.com/company/gigasavvy> Twitter
<https://twitter.com/gigasavvy> <http://www.gigasavvy.com/>

**Comment by lstellway** [comment]
Hello @crowtower !

Thank you for the suggestion - I'm glad you like the project 😄 

I remember playing with the transitions before publishing - I tried implementing your suggestions and (as before) I experienced some strange performance issues in Chrome. Do you see the same issue? Safari looks amazing. 

Until I or someone else finds a fix for the performance issue, I figured I would leave it to individuals to implement transitions if they wanted. Another idea is to add a configuration option in the JS. 

What do you think?

**Comment by crowtower** [comment]
Hi Logan, thanks for the reply!

What performance issues do you have? I only tested it on Chrome and it works very smoothly for me - I found your current version is quite jittery without the transition. 

Only slight issue is that the position starts from top left corner, so if you start hovering in the bottom right of the image it does a very quick slide toward that part of the image as it fades in, but it's subtle enough not to worry about.

Perhaps the configuration option might be worthwhile and let people decide for themselves? I really just added my comment as a suggestion to try, and if someone saw it here they could modify their instance of your plugin to suit themselves.

Well done on a great plugin! Cheers, Erik

**Comment by lstellway** [comment]
Thanks Erik! 

It may just be my computer, but the transitions are glitchy when I have CSS3 transitions. I'll play with it some more.

Also: great point on the starting point of the image. It would probably be great to set the position before fading the image in - I'll try to make some time soon to make an update.

Best! Logan
