### ISSUE TITLE
how to apply callback

### ISSUE THREAD

**Issue by YvonneD** [loganstellway/ZoomIt#7]
Hi. How to apply callbback function such as onClick(). Would you please give me a demo. I wanna do when I click, then crop the zoomed image and show on the screen. Thanks

**Comment by lstellway** [comment]
Hi @YvonneD !

You can apply a click event like so:
```
$('#zoomit-target').zoomIt({
    onClick: function(){
        console.log('Clicked!');
    }
});
```

Hopefully this will help you get the ball rolling on the functionality you need! I will release another version soon that will provide the event data to the callback function.
